spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: start@123
    url: jdbc:mysql://localhost:3306/olx_users
    username: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zendb
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
user:
  login:
    name: sagar
